### ISSUE TITLE
simple example not working

### ISSUE THREAD

**Issue by hyuen** [openai/blocksparse#1]
I am using cuda-8.0, tensorflow 1.4.1 on ubuntu 16.04 and when trying to run the example, I get the following:

This is running on a gtx 960m, when running on a gtx 1060 it runs fine, is the 960m supported?

(ml) hyz@hyz-XPS-15-9550:~/prog/blocksparse/examples$ python simple.py 
2017-12-08 11:06:57.447347: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-08 11:06:57.560860: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-12-08 11:06:57.561241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 960M major: 5 minor: 0 memoryClockRate(GHz): 1.0975
pciBusID: 0000:01:00.0
totalMemory: 1.96GiB freeMemory: 1.55GiB
2017-12-08 11:06:57.561274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2017-12-08 11:06:59.663068: W tensorflow/core/framework/op_kernel.cc:1192] Internal: invalid resource handle
Traceback (most recent call last):
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: invalid resource handle
	 [[Node: BlocksparseMatMul_000000 = BlocksparseMatmul[C=4096, K=4096, alpha=1, axis=1, bench=0, beta=0, blocks=8168, bshift=5, dtype_dw=DT_FLOAT, dtype_w=DT_FLOAT, dtype_x=DT_FLOAT, dtype_y=DT_FLOAT, locks=0, locks_dx=0, segments=128, segments_dx=128, shared=608, shared_dx=656, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_Placeholder_0_0/_1, w/read, BlocksparseMatMul/fprop_lut/_3, BlocksparseMatMul/bprop_lut/_5, BlocksparseMatMul/updat_lut/_7)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "simple.py", line 27, in <module>
    result = sess.run([y], feed_dict = {x: np.ones((minibatch_size,hidden_size), dtype='float32')})
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: invalid resource handle
	 [[Node: BlocksparseMatMul_000000 = BlocksparseMatmul[C=4096, K=4096, alpha=1, axis=1, bench=0, beta=0, blocks=8168, bshift=5, dtype_dw=DT_FLOAT, dtype_w=DT_FLOAT, dtype_x=DT_FLOAT, dtype_y=DT_FLOAT, locks=0, locks_dx=0, segments=128, segments_dx=128, shared=608, shared_dx=656, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_Placeholder_0_0/_1, w/read, BlocksparseMatMul/fprop_lut/_3, BlocksparseMatMul/bprop_lut/_5, BlocksparseMatMul/updat_lut/_7)]]

Caused by op 'BlocksparseMatMul_000000', defined at:
  File "simple.py", line 22, in <module>
    y = bsmm(x, w)
  File "/home/hyz/prog/blocksparse/blocksparse/matmul.py", line 383, in __call__
    shared=self.fprop_shared, shared_dx=self.bprop_shared, bench=bench, name=name
  File "<string>", line 631, in blocksparse_matmul
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/hyz/ml/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): invalid resource handle
	 [[Node: BlocksparseMatMul_000000 = BlocksparseMatmul[C=4096, K=4096, alpha=1, axis=1, bench=0, beta=0, blocks=8168, bshift=5, dtype_dw=DT_FLOAT, dtype_w=DT_FLOAT, dtype_x=DT_FLOAT, dtype_y=DT_FLOAT, locks=0, locks_dx=0, segments=128, segments_dx=128, shared=608, shared_dx=656, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_Placeholder_0_0/_1, w/read, BlocksparseMatMul/fprop_lut/_3, BlocksparseMatMul/bprop_lut/_5, BlocksparseMatMul/updat_lut/_7)]]

**Comment by hyuen** [comment]
The compute capability of the 960 is 5.0 while the one for 1060 is 6.1

**Comment by scott-gray** [comment]
Sorry, I should have realized sm_50 hardware was still being used.  For Maxwell I only have it compiled for sm_52.  This is easily fixed.  Just update this line to major, minor = 5, 0

https://github.com/openai/blocksparse/blob/master/generate_kernels.py#L241

And change the arch=compute_52,code=sm_52 compiler flags here to arch=compute_50,code=sm_50

https://github.com/openai/blocksparse/blob/master/Makefile#L28

Then go ahead an rebuild to see if that fixes things.  I'll update this in the next release.

**Comment by scott-gray** [comment]
added the above changes.
