### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'resource_loader'

### ISSUE THREAD

**Issue by GregoryVPerry** [openai/blocksparse#39]
Ubuntu 18.04 LTS clean install and fully updated, after a pip3 install of tensorflow-gpu and install of blocksparse from source I am getting the following error:

Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import blocksparse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gperry/DeepFlight/OpenAI/blocksparse/blocksparse/__init__.py", line 3, in <module>
    from blocksparse.utils import (
  File "/home/gperry/DeepFlight/OpenAI/blocksparse/blocksparse/utils.py", line 15, in <module>
    data_files_path = tf.resource_loader.get_data_files_path()
AttributeError: module 'tensorflow' has no attribute 'resource_loader'

**Comment by galina0217** [comment]
Same issue. Is there any solution?

**Comment by GregoryVPerry** [comment]
The team is still recuperating from the $1 billion Gates investment hangovers apparently. :)

**Comment by sedrickkeh** [comment]
Try doing ```tf.compat.v1.resource_loader``` instead of ```tf.resource_loader``` in the ```utils.py``` file.
