### ISSUE TITLE
ValueError: Invalid aggregation_method specified 3.

### ISSUE THREAD

**Issue by fortianyou** [openai/blocksparse#4]
The test `blocksparse_matmul_bench.py` meet error with reports:

```
Traceback (most recent call last):
  File "./blocksparse_matmul_bench.py", line 100, in <module>
    d = tf.gradients(y, [x, w], e, aggregation_method=3)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 533, in gradients
    out_grads = _AggregatedGrads(grads, op, loop_state, aggregation_method)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 820, in _AggregatedGrads
    aggregation_method)
ValueError: Invalid aggregation_method specified 3.
```

It seems that `aggregation_method=3` is illegal according to official document of tensorflow [https://www.tensorflow.org/api_docs/python/tf/AggregationMethod](url). 

So, what value should be set to `aggregation_method` ?

If I use erase the fourth parameter `aggregation_method`, and run the test again. A TypeError occur

```
Traceback (most recent call last):
  File "blocksparse_matmul_bench.py", line 101, in <module>
    d = tf.gradients(y, [x, w], e)# aggregation_method=3)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 533, in gradients
    out_grads = _AggregatedGrads(grads, op, loop_state, aggregation_method)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 872, in _AggregatedGrads
    out_grads[i] = _MultiDeviceAddN(out_grad)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 767, in _MultiDeviceAddN
    summands.append(math_ops.add_n(tensors))
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 2000, in add_n
    return gen_math_ops._add_n(inputs, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 220, in _add_n
    "AddN", inputs=inputs, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 598, in _apply_op_helper
    param_name=input_name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'inputs' has DataType bfloat16 not in list of allowed values: float32, float64, int64, int32, uint8, uint16, int16, int8, complex64, complex128, qint8, quint8, qint32, float16, variant
```

**Comment by scott-gray** [comment]
Sorry for the late reply, I didn't realize I wasn't watching the repo.  Anyway, if you look in:

https://github.com/openai/blocksparse/blob/master/vendor/tensorflow_bfloat16_patch/tensorflow/python/ops/gradients_impl.py#L872

you'll see how I defined a custom aggregation mode to support bfloat16.  I'm not sure if this custom code is needed anymore if you use the master branch of tf (most of my changes were merged in).
